### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by BigJackz** [tspaanan/shoplist-gener#1]
Projektin koodi ladattu 4.5 klo 19:12.
Koodi näytti ainakin omaan silmään ihan hyvälle, kommenttejakin oli ihan ok määrä. Kuitenkin kommentteja voisi olla aina enemmän varsinkin ShoplistgenerDAOsqlite.java:ssa, mutta koska javadocia on tehty, niin ei se haittaa niin paljoa. Koodi on joissain osin vähän heikosti ymmärrettävissä, niinkuin olet itsekin kommentoinut esimerkiksi Ingredient.java sortIngredients metodissa. Koodissa on saatu hyvin eriteltyä sovelluslogiikka käyttöliittymästä. Käyttöliittymän koodiin olisi voinut ehkä lisätä muutamia kommentteja enemmän, mutta en ole ihan varma olisiko se edes tarpeen, mutta ei niistä varmaan haittaakaan olisi. Koodin metodien nimet ovat hyvät, sillä ne kertovat aikalailla mitä ne tekevätkin. Ei minulla oikein ole koodin suhteen parannusehdotuksia. Hyvälle vaikuttaa!

**Comment by tspaanan** [comment]
Kiitos palautteesta, on aina hyvä kuulla muiden näkymyksiä oman koodin laadusta! Viimeinen palautus on nyt koodin osalta toivottavasti selkein tähän mennessä :)
